# Generated by Django 4.2 on 2023-06-27 16:02

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('courseCode', models.CharField(max_length=10, primary_key=True, serialize=False, unique=True)),
                ('courseName', models.CharField(max_length=50)),
                ('courseCredit', models.IntegerField(default=0, validators=[django.core.validators.MaxValueValidator(4)])),
                ('maxCarryMark', models.IntegerField(null=True, validators=[django.core.validators.MaxValueValidator(70)])),
            ],
        ),
        migrations.CreateModel(
            name='Lecturer',
            fields=[
                ('lecturerID', models.CharField(max_length=10, primary_key=True, serialize=False, unique=True)),
                ('lecturerName', models.CharField(max_length=50)),
                ('password', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('matricID', models.CharField(max_length=10, primary_key=True, serialize=False, unique=True)),
                ('studentName', models.CharField(max_length=50)),
                ('currentSemester', models.CharField(default='1', max_length=1, validators=[django.core.validators.MaxValueValidator(4)])),
                ('password', models.CharField(max_length=50)),
                ('mentorID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='carrytrack.lecturer')),
            ],
        ),
        migrations.CreateModel(
            name='CarryMark',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('assesment1', models.IntegerField(default=0, null=True, validators=[django.core.validators.MaxValueValidator(30)])),
                ('assesment2', models.IntegerField(default=0, null=True, validators=[django.core.validators.MaxValueValidator(30)])),
                ('assesment3', models.IntegerField(default=0, null=True, validators=[django.core.validators.MaxValueValidator(30)])),
                ('assesment4', models.IntegerField(default=0, null=True, validators=[django.core.validators.MaxValueValidator(30)])),
                ('is_reviewed', models.BooleanField(default=False)),
                ('remarks', models.TextField(blank=True, null=True)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='carrytrack.course')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='carrytrack.student')),
            ],
        ),
    ]
