# Generated by Django 4.2 on 2023-06-27 16:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carrytrack', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='studentPhone',
            field=models.CharField(max_length=2, null=True),
        ),
    ]
