# Generated by Django 4.2 on 2023-06-27 22:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carrytrack', '0002_student_studentphone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carrymark',
            name='is_reviewed',
            field=models.BooleanField(null=True),
        ),
    ]
