# Generated by Django 4.2 on 2023-06-28 22:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carrytrack', '0004_alter_carrymark_unique_together'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='studentPhone',
            field=models.CharField(max_length=12, null=True),
        ),
    ]
