# Generated by Django 4.2 on 2023-06-28 22:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carrytrack', '0005_alter_student_studentphone'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='studentImage',
            field=models.ImageField(default='media/blank-person.jpg', upload_to='media'),
        ),
    ]
