# Generated by Django 4.2 on 2023-06-29 06:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carrytrack', '0010_alter_student_studentimage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='studentImage',
            field=models.ImageField(null=True, upload_to='media'),
        ),
    ]
