# Generated by Django 4.2 on 2023-06-30 18:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('carrytrack', '0011_alter_student_studentimage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='mentorID',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='carrytrack.lecturer'),
        ),
    ]
